### PR TITLE
Update API Reference Spec

### PR DESCRIPTION
**Pull request by dustinlarimer**
This PR updates the *modified static copy* of our API Reference with the latest available here: https://api-play.paas.macrometa.io/_admin/api/swagger.json

### CODE REVIEW

**Review by diana-macrometa — APPROVED** [review]

**Comment by dustinlarimer** [comment]
@joubert-macrometa updating this file makes me nervous, for reasons we've discussed. Can you give this diff a look?

**Comment by diana-macrometa** [comment]
@dustinlarimer, did you have to do any processing or merging?

**Comment by dustinlarimer** [comment]
@diana-macrometa yeah, the diff isn't loading here, unfortunately, but we maintain these extra fields at the top of the file to improve the in-app presentation for the rendered reference. These are not part of the hosted swagger file, so they get overwritten whenever we drop in a new/latest version. They need to be manually copy/pasted back into place before committing the final version locally. Super messy.

```
  "host": "api-play.paas.macrometa.io",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "servers": [
    {
      "url": "api-play.paas.macrometa.io",
      "description": "Production server"
    }
  ],
  "securityDefinitions": {
    "ApiKeyAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
...
```

**Comment by diana-macrometa** [comment]
What about all the wacky schemas at the end, like the Stripe ones? Do they need to be deleted or hidden somehow?

**Comment by dustinlarimer** [comment]
> What about all the wacky schemas at the end, like the Stripe ones? Do they need to be deleted or hidden somehow?

@diana-macrometa I don't have an answer for that, but this is probably an upstream question about the reference in general.

**Comment by dustinlarimer** [comment]
@joubert-macrometa @diana-macrometa updated to include the latest file, plus a script and some documentation for future contributors.

**Review by joubert-macrometa — APPROVED** [review]

**Pull request merged**
