### PR TITLE
18.00 Instances Metadata Update

### PR DESCRIPTION
**Pull request by diana-macrometa**
This PR adds content for [CEP-617](https://macrometa.atlassian.net/browse/CEP-617) to the documentation.

@StoyanTc, please take a close look at the new example! I didn't see a code example in the ticket, so I am totally guessing and it is probably wrong. Please also make sure that the content is correct. The ticket was sparse, so I am not confident in the text I wrote.

[CEP-617]: https://macrometa.atlassian.net/browse/CEP-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by StoyanTc — COMMENTED** [review]
No changes are required into the documentation but only into the release notes.
The parameter `distributed` wasn't implemented as redundant.

**Comment by diana-macrometa** [comment]
Then what changed? Do we just always run stream workers on multiple nodes automatically?

**Comment by StoyanTc** [comment]
> Then what changed? Do we just always run stream workers on multiple nodes automatically?

The internal rebalancing of the stream workers among the nodes was changed, i.e. all instances of given stream worker were run only on one node before and after the fix are subject of evenly distribution on all available node.

**Comment by diana-macrometa** [comment]
Updated.

**Review by StoyanTc — APPROVED** [review]

**Pull request merged**
