### PR TITLE
fix broken links in CEP section

### PR DESCRIPTION
**Pull request by elof**

### CODE REVIEW

**Comment by dustinlarimer** [comment]
@elof one more
```
On source page path = /docs/cep/query-guide/query:
    linking to /docs/cep/query-guide/named-aggregation
```

**Comment by elof** [comment]
@dustinlarimer the fix I did in this PR is working for me locally

**Comment by dustinlarimer** [comment]
@elof I fixed up that last link - it was showing up in the Vercel build log. 

I also set broken link behavior to throw errors from now on, to surface these during the PR process. /cc @diana-macrometa @jamesm-macrometa @dlozina-macrometa

**Review by dustinlarimer — APPROVED** [review]

**Comment by diana-macrometa** [comment]
Thanks, Dustin! I had a note to fix these tomorrow, but getting an
error message is much better than having to remember to run a build and
check for broken links.

**Pull request merged**
