### PR TITLE
17.16 - BigQuery Connector

### PR DESCRIPTION
**Pull request by diana-macrometa**
This PR documents prerequisites and special considerations for using the BigQuery connector.

**Reviewers**

Please add anything I have missed. If there are little tricks or gotchas, this is the place to note them.

### CODE REVIEW

**Comment by grainier-macrometa** [comment]
@diana-macrometa - We need to include information that can be found at [1] & [2].

[1] https://github.com/Macrometacorp/macrometa-source-collection/blob/main/GETTING_STARTED.md
[2] https://github.com/Macrometacorp/macrometa-target-collection/blob/main/GETTING_STARTED.md

**Review by grainier-macrometa — COMMENTED** [review]
@diana-macrometa - We need to include information that can be found at [1] & [2].

[1] https://github.com/Macrometacorp/macrometa-source-bigquery/blob/main/GETTING_STARTED.md
[2] https://github.com/Macrometacorp/macrometa-target-bigquery/blob/main/GETTING_STARTED.md

**Comment by diana-macrometa** [comment]
@grainier-macrometa - BigQuery did not have any additional requirements noted. Is there additional information you would like me to add?

**Comment by koshy-thomas** [comment]
@diana-macrometa @grainier-macrometa @praminda-macrometa, One thing to note here is that BigQuery "Source" Connector only supports FULL_TABLE replication method and it is used directly as default (user is not asked to provide replication method here since only FULL_TABLE is supported). LOG_BASED is not supported in BigQuery Source connector

**Comment by diana-macrometa** [comment]
Good catch, @koshy-thomas! I added a bit about the replication types.

**Review by grainier-macrometa — APPROVED** [review]

**Pull request merged**
