### PR TITLE
Doc 360 Break up CLI commands

### PR DESCRIPTION
**Pull request by diana-macrometa**
- Separated the CLI commands topic into separate topics.
- Minor format changes throughout, but no content changes.
- A Jira ticket exists to remind us to go back and improve these files in the future.

### CODE REVIEW

**Comment by diana-macrometa** [comment]
@dustinlarimer, any idea why Vercel deployment failed here?

**Comment by diana-macrometa** [comment]
NVM, @dustinlarimer. I think it was broken links, it just did not tell me that.

**Comment by dustinlarimer** [comment]
@diana-macrometa Was this destination path changed?
Screen Shot 2022-07-22 at 9 43 46 AM

**Comment by diana-macrometa** [comment]
@dustinlarimer, yes. I fixed that just now.

**Pull request merged**
