### PR TITLE
change case of file names

### PR DESCRIPTION
**Pull request by elof**
This PR changes the case for folders and files that were capitalized to lower case

### CODE REVIEW

**Review by diana-macrometa — APPROVED** [review]
Thank you! I was just going to change them as we touched them. :)

**Comment by diana-macrometa** [comment]
Any idea why the check is failing?

**Comment by elof** [comment]
It looks like docusarus is recognizing both Capital.md and capital.md as the same route. Looking into it

**Comment by diana-macrometa** [comment]
Yeah, it does that. I usually make a change to the tense at the same time as I change the content. That seems to goose it into actually doing the update.

Also, GitHub doesn't recognize changing the file capitalization as a change, IIRC. Makes it even more annoying.

**Comment by elof** [comment]
I think Nick ran into this same problem and found out that it was because github actions keeps a cache of the file name route paths. I think we might need to wait until the cache clears, because if I remember correctly there isn't a way to force github actions cache to clear

**Comment by elof** [comment]
I did some research. If this is related to cache then it will reset in 7 days. There is a way to reset the cache but it requires admin rights. Since this isn't critical I suggest we let it be for now and try to run the build again next week

**Comment by elof** [comment]
closing this as the other PR fixed the cases

**Pull request closed without merging**
