### PR TITLE
17.17 Quantization concept topic

### PR DESCRIPTION
**Pull request by diana-macrometa**
This PR adds a topic explaining the concept of quantization and the options Macrometa GDN currently offers.

### CODE REVIEW

**Comment by maheshw2** [comment]
I don't find anything to review in this PR.

**Comment by diana-macrometa** [comment]
> I don't find anything to review in this PR.

Whoops! I sure messed that up. Anyway, I copied the file I want you to review. Please review it, then I'll remove the "copy" text when I merge it.

**Comment by maheshw2** [comment]
> > I don't find anything to review in this PR.
> 
> Whoops! I sure messed that up. Anyway, I copied the file I want you to review. Please review it, then I'll remove the "copy" text when I merge it.

I'm still not able to see any diff in this PR.

**Comment by diana-macrometa** [comment]
Grr. I will remake the PR.

**Pull request closed without merging**
