### PR TITLE
17.16 Snowflake connector

### PR DESCRIPTION
**Pull request by diana-macrometa**
This PR documents prerequisites and special considerations for using the Snowflake connector.

**Reviewers**

Please add anything I have missed. If there are little tricks or gotchas, this is the place to note them.

### CODE REVIEW

**Review by grainier-macrometa — COMMENTED** [review]
@diana-macrometa - We need to include information that can be found at [1] & [2].

[1] https://github.com/Macrometacorp/macrometa-source-snowflake/blob/main/GETTING_STARTED.md
[2] https://github.com/Macrometacorp/macrometa-target-snowflake/blob/main/GETTING_STARTED.md

**Comment by diana-macrometa** [comment]
@grainier-macrometa - I did not include information about the fields because the field descriptions are in the UI already. It would be redundant. Other information, such as running Enterprise Edition or higher, is included. Is there anything else that should be added?

**Comment by diana-macrometa** [comment]
Reviewers, please review.

**Review by grainier-macrometa — APPROVED** [review]

**Comment by grainier-macrometa** [comment]
@diana-macrometa - Approved. I agree. For the UI it's sufficient. However, if the user decides to use the API, they should at least know the required configs. Anyway, we can discuss on that and make changes if required for upcoming releases.

cc: @rahulprabhune-macrometa @dlozina @praminda-macrometa @koshy-thomas

**Comment by diana-macrometa** [comment]
Agreed, @grainier-macrometa. This documentation will continue to develop as the product matures out of beta and CLI and SDK support is added. @dlozina was looking at making a "smart SDK" to provide a simpler way for users to interact with connectors in a code-based way as well.

**Pull request merged**
