### PR TITLE
Remove or hide this page

### PR DESCRIPTION
**Pull request by Luba89**
Currently, users can't see or change any limits on our platform; I think this page should be removed.

### CODE REVIEW

**Review by diana-macrometa — CHANGES_REQUESTED** [review]
@mikeridley, @elof, @durgagokina, need some context here. 

Are we planning on doing anything with these limits in the future? Is this information useful to users at all?

Options are:
1. Leave this topic as-is.
2. Delete this topic.
3. Hide this topic but leave it here so we can unhide it later.

**Comment by diana-macrometa** [comment]
@Luba89, please answer the questions.

**Comment by Luba89** [comment]
> @Luba89, please answer the questions.

@diana-macrometa Users can't change the Stream Workers limits and can't see the page for changing limits. I would remove this page, but we can save it as an internal doc.

**Review by diana-macrometa — APPROVED** [review]
Sound good to me. Please make sure this content is saved somewhere that people who need it can access it.

**Pull request merged**
