### PR TITLE
Update P3 index.md

### PR DESCRIPTION
**Pull request by diana-macrometa**
This PR adds a feature list to the P3 Landing page.

### CODE REVIEW

**Review by db-macrometa — CHANGES_REQUESTED** [review]
So far we don't have anything pertaining to **image compression** or any image optimizations for that matter under Advanced Compression Techniques

**Comment by diana-macrometa** [comment]
> So far we don't have anything pertaining to **image compression** or any image optimizations for that matter under Advanced Compression Techniques

If you give me something for the list, I am happy to add it. This is the list I was given, and it seems to match what is in the UI.

Keep in mind, if we have things in the docs, then we will need to tell the user how they can enable them (API, UI, or talk to MM).

**Comment by db-macrometa** [comment]
I don't think we have any UI or API that would suggest that we support image compression or optimization @diana-macrometa Unless I missed it, you can safely remove this specific wording, i.e image compression and just leave content compression.

**Comment by diana-macrometa** [comment]
> I don't think we have any UI or API that would suggest that we support image compression or optimization @diana-macrometa Unless I missed it, you can safely remove this specific wording, i.e image compression and just leave content compression.

AH, I misunderstood what you were saying. This is why I suggest that editors use the Git tools to specifically comment and suggest on the line where they want changes, because that helps prevent misunderstanding.
image

**Comment by diana-macrometa** [comment]
All right, I updated what I think you were referring to. Anything else?

**Review by edgargarciamacrometa — COMMENTED** [review]
👍

**Review by db-macrometa — APPROVED** [review]

**Pull request merged**
