### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by jgaonakm**
Remove a variable causing an error on the JS code sample

### CODE REVIEW

**Comment by diana-macrometa** [comment]
Support guys, please review.

**Comment by jesusgonzalez12** [comment]
@diana-macrometa, the thisApikey constant can be defined right after the globalUrl one on line 67 and then be referenced on line 92 with the client constant.
This is a way to show the user that they logged in with that API key.

If you think that's not necessary, deleting the `,  user: ${thisApikey}` is the way to go.

**Review by koshy-thomas — APPROVED** [review]

**Comment by koshy-thomas** [comment]
Approved (there's no variable thisApiKey, and it's not needed) so we can go ahead with this!

**Comment by koshy-thomas** [comment]
Thanks @jgaona-akamai !

**Review by diana-macrometa — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
