### PR TITLE
Create p3-optimizations.md

### PR DESCRIPTION
**Pull request by diana-macrometa**
This PR adds a page explaining P3 optimizations.

### CODE REVIEW

**Review by db-macrometa — CHANGES_REQUESTED** [review]
1) Under Minify CSS, the bold section is not correct and should be removed.
_Minification **also simplifies CSS, potentially making it easier for developers to manage and update styles** while decreasing the bandwidth needed for CSS file transfers._

2) Under Minify JS, the bold section I think would rather be removed:
_Beyond reducing file size, **minification can also obscure code, providing a slight layer of obfuscation against casual observation or copying, though this is not a substitute for secure coding practices.**_

**Comment by diana-macrometa** [comment]
> 1. Under Minify CSS, the bold section is not correct and should be removed.
>    _Minification **also simplifies CSS, potentially making it easier for developers to manage and update styles** while decreasing the bandwidth needed for CSS file transfers._
> 2. Under Minify JS, the bold section I think would rather be removed:
>    _Beyond reducing file size, **minification can also obscure code, providing a slight layer of obfuscation against casual observation or copying, though this is not a substitute for secure coding practices.**_

Thanks @db-macrometa! In future, if you click the plus sign on a line and then the icon, then you can directly suggest in the text. This is WAY easier for all involved.
image

**Comment by edgargarciamacrometa** [comment]
@diana-macrometa - Looks good 👍

**Comment by diana-macrometa** [comment]
Is that an approval to deploy this page? If so, please approve.

**Review by edgargarciamacrometa — APPROVED** [review]

**Review by db-macrometa — APPROVED** [review]

**Pull request merged**
