### PR TITLE
Doc 304 - Document Store Updates

### PR DESCRIPTION
**Pull request by diana-macrometa**
Breaking up this PR, it is getting kind of long.

- Added View Collections
- Added Document Store Data
- Edited several other topics
- Hid two other files (that's the ones with underscores) so they will not show in the build. I will add content in a separate PR.

### CODE REVIEW

**Review by elof — APPROVED** [review]
:shipit:

**Review by dustinlarimer — COMMENTED** [review]
The screenshot included in this PR has an empty space. This may have undesired side effects with dark mode, and appear fine in light mode.

Screen Shot 2022-07-12 at 5 31 40 PM

**Comment by diana-macrometa** [comment]
Image updated, @dustinlarimer

**Review by dustinlarimer — APPROVED** [review]

**Comment by jamesm-macrometa** [comment]
👍

**Pull request merged**
