### PR TITLE
Update Stream REST APIs example

### PR DESCRIPTION
**Pull request by diana-macrometa**
Edited the Stream REST APIs topic a bit, noticed some problems. This PR is in DRAFT until they get worked out.

- Changed the example intro
- Renamed the topic to REST APIs Stream Example
- Minor edits to Messages topic. (Reviewers, don't worry too much about this one.)

REVIEWERS -
- Please rewrite the authentication part so that it uses an API key rather than JWT or email/password.
- Check the code thoroughly. I did not write this, I have no idea how old it is.

### CODE REVIEW

**Comment by diana-macrometa** [comment]
@koshy-thomas - I used the code blocks you gave me for the other PR and I think I have updated these to run with API keys. Please take a look.

Also, please check the import list. There might be unnecessary libraries like there were in some of the other PRs.

**Comment by edgargarciamacrometa** [comment]
I think the base code has some syntax issues, like try block expected or delete the orphan catch, and the run function is not wrapping the whole code. This is a possible solution. 
```
const WebSocket = require('ws');
class APIRequest {
  _headers = {
    Accept: 'application/json',
    'Content-Type': 'application/json'
  };

  constructor(url, apikey) {
    this._url = url;
    this._headers.authorization = `apikey ${apikey}`;
  }

  _handleResponse(response, resolve, reject) {
    if (response.ok) {
      resolve(response.json());
    } else {
      reject(response);
    }
  }

  req(endpoint, { body, ...options } = {}) {
    const self = this;
    return new Promise(function (resolve, reject) {
      fetch(self._url + endpoint, {
        headers: self._headers,
        body: body ? JSON.stringify(body) : undefined,
        ...options
      }).then((response) => self._handleResponse(response, resolve, reject));
    });
  }
}

const apikey = '';
const federationName = 'api-gdn.paas.macrometa.io';
const federationUrl = `https://${federationName}`;

const stream = 'api_tutorial_streams';
const consumerName = 'api_tutorial_streams_consumer';
const isGlobal = true;
const tenant = '';

const run = async function () {
  try {
    const connection = new APIRequest(federationUrl, apikey);

    /* -------------------- Connect to GDN -------------------- */

    console.log('Login Successfully using', tenant);
    /* ------------------------------ Create Stream ----------------------------- */

    try {
      await connection.req(
        `/_fabric/_system/streams/${stream}?global=${isGlobal}`,
        {
          body: { name: stream },
          method: 'POST'
        }
      );
      console.log('Stream created successfully');
    } catch (e) {
      if (e.status === 409) {
        console.log('Stream already exists, skipping creation of stream');
      } else {
        console.log('Error while creating stream');
        throw e;
      }
    }

    /* ----------------- Publish and Subscribe Message to Stream ---------------- */

    const region = isGlobal ? 'c8global' : 'c8local';
    const streamName = `${region}s.${stream}`;

    // Fetching local URL in case the stream is local
    const localDcDetails = await connection.req(`/datacenter/local`, {
      method: 'GET'
    });

    const dcUrl = localDcDetails.tags.url;

    const url = isGlobal ? federationName : `api-${dcUrl}`;

    const otpConsumer = await connection.req(`/apid/otp`, {
      method: 'POST'
    });
    const otpProducer = await connection.req(`/apid/otp`, {
      method: 'POST'
    });

    const consumerUrl = `wss://${url}/_ws/ws/v2/consumer/persistent/${tenant}/${region}._system/${streamName}/${consumerName}?otp=${otpConsumer.otp}`;

    const producerUrl = `wss://${url}/_ws/ws/v2/producer/persistent/${tenant}/${region}._system/${streamName}?otp=${otpProducer.otp}`;

    let consumer;
    let producer;
    let producerInterval;

    /* -------------------------- Initialize Consumer -------------------------- */

    const initConsumer = () => {
      return new Promise((resolve) => {
        consumer = new WebSocket(consumerUrl);

        consumer.onopen = function () {
          console.log('WebSocket:Consumer is open now for ' + streamName);
          resolve();
        };

        consumer.onerror = function () {
          console.log(
            'Failed to establish WebSocket:Consumer connection for ' +
              streamName
          );
        };

        consumer.onclose = function () {
          console.log('Closed WebSocket:Consumer connection for ' + streamName);
        };

        consumer.onmessage = function (message) {
          const receivedMsg = message.data && JSON.parse(message.data);

          console.log(
            `WebSocket:Consumer message received at ${new Date()}`,
            receivedMsg
          );

          const ackMsg = { messageId: receivedMsg.messageId };
          consumer.send(JSON.stringify(ackMsg));
        };
      });
    };

    /* -------------------------- Initialize Producer -------------------------- */

    const initProducer = () => {
      producer = new WebSocket(producerUrl);

      producer.onopen = function () {
        console.log('WebSocket:Producer is open now for ' + streamName);
        producerInterval = setInterval(function () {
          console.log(`WebSocket:Producer message sent at ${new Date()}`);
          producer.send(JSON.stringify({ payload: `test` }));
        }, 10000);
      };

      producer.onclose = function (e) {
        console.log('Closed WebSocket:Producer connection for ' + streamName);
        clearInterval(producerInterval);
      };

      producer.onerror = function (e) {
        console.log(
          'Failed to establish WebSocket:Producer connection for ' + streamName
        );
      };
    };

    initConsumer().then(() => {
      initProducer();
    });

    await new Promise((resolve) => setTimeout(resolve, 1 * 40 * 1000));
    consumer.close();
    console.log('Closing consumer...');
    producer.close();
    console.log('Closing producer...');
    await new Promise((resolve) => setTimeout(resolve, 5000));
    /* ------------------------ Unsubscribe from Stream ------------------------ */
    const consumerUnsubscribe = await connection.req(
      `/_fabric/_system/_api/streams/subscription/${consumerName}`,
      {
        method: 'DELETE'
      }
    );
    console.log(
      `${consumerName} unsubscribed successfully`,
      consumerUnsubscribe
    );
    /* ------------------------------ Delete Topic ------------------------------ */
  } catch (e) {
    console.error(e);
  }
};

run();
```

**Comment by koshy-thomas** [comment]
I have added the working python REST API code in the above two commits. The consumer url was wrong it was making a producer connection instead of consumer connection and there was a problem in the way the acknowledgement was sent and received added threading to simulate the producer and consumer as well as the acknowledgement of message

**Comment by koshy-thomas** [comment]
I have fixed the code for Javascript REST API in the above three commits. @diana-macrometa basically, while editing the "run" function (removing login from email, password and adding apikeys) some parts of the code were broken. But indeed you did use apikey correctly 👍

**Review by koshy-thomas — APPROVED** [review]

**Pull request merged**
