### PR TITLE
Changes to document x-gdn-requestid and x-gdn-region in the response …

### PR DESCRIPTION
**Pull request by nitinanand-macrometa**
Changes to add API-173 in the release notes for 0.17.10. Also added exact header for API-178

### CODE REVIEW

**Comment by nitinanand-macrometa** [comment]
@diana-macrometa How does the swagger.json in docs get updated? Is there a process for it?

**Comment by diana-macrometa** [comment]
> @diana-macrometa How does the swagger.json in docs get updated? Is there a process for it?

I do not know, but @joubert-macrometa might.

**Comment by joubert-macrometa** [comment]
@diana-macrometa I think he is asking how the doc website picks up these changes.

**Comment by diana-macrometa** [comment]
Automatically somehow. I do not know the details.

**Pull request closed without merging**
