### PR TITLE
Add doc for support of native apps.

### PR DESCRIPTION
**Pull request by joubert-macrometa**
We have never documented how a native app (iOS, Android, etc) can used with the waiting room, because we were missing a usable API. This PR documents the new "position" API and how to use it.

### CODE REVIEW

**Comment by diana-macrometa** [comment]
@joubert-macrometa , please add a description explaining what changed. I see the API spec changed a great deal.

For the native app file, what is the purpose of the file? Is it much different than the getting started content? It seems a bit redundant, so I want to understand how it adds value to the documentation.

**Comment by joubert-macrometa** [comment]
@diana-macrometa I am getting @todor-macrometa to review the api spec.  It should be a few lines added only, so don't understand why these massive changes.

**Comment by joubert-macrometa** [comment]
We have never documented how a native app (iOS, Android, etc) can used with the waiting room, because we were missing a usable API.  This PR documents the new "position" API and how to use it.

**Comment by diana-macrometa** [comment]
In that case, let's have a page explaining the position API, what it is and why to use it. 

Right now, the topic really only mentions position in passing. The rest of it talks about "native apps," and I do not understand how this is different than any of the rest of our documentation. I think we could potentially work some of it, especially the explanation and pseudocode, into the [Get Started with VWRs](https://www.macrometa.com/docs/photoniq/vwrs/get-started-vwrs) topic, which right now is pretty sparse. 

The best practices could also be their own topic, VWRs Best Practices, as they seem pretty generic.

**Comment by joubert-macrometa** [comment]
Supporting native apps is a special case.  It is a replacement for the web browser.

The getting started guide seems to be how you configure the edgeworker and the vwrs.

But Native apps have nothing to do with that.  That is why I separated it.  It is used by external clients who interact with the waiting room that are not a web browser.

The API is documented in vwrs-sepc.json.  But we need to fix it because it has all these changes that should not be there.  Hopefully, that will be fixed in the next 24 hours.  

We might need to go to voice for me to explain it better.

**Comment by joubert-macrometa** [comment]
Not using since it is being done in a different PR.

**Pull request closed without merging**
